routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::resource('articles','ArticleController');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'name', 'content'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use Illuminate\Http\Request;
use App\Http\Requests\ArticleStoreRequest;

class ArticleController extends Controller
{

    public function index()
    {
        $articles = Artricle::all();
        return view('home',['articles'=>$articles]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('articles_create');
    }



    public function store(ArticleStoreRequest $request)
    {
        $data = $request->validated(); 
        Article::create($data);
        return redirect('/')->with('success','Article Added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        $articles = Article::find($article->id);
        return view('articles_show',['articles'=>$articles]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        $articles = Article::find($article->id);
        return view('articles_edit',['articles'=>$articles]);        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleStoreRequest $request, Article $article)
    {
        
        $article->name = $request->name;
        $article->content = $request->content;
        $article->save();
        return redirect('/')->with('success','Article updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return redirect('/')->with('success','Article Deleted successfully');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;

class HomeController extends Controller
{
    public function index(){
        $articles= Article::paginate(5);
        return view('home',['articles'=>$articles]);
    }

}

resources/views/articles_create.blade.php
@extends('master')

@section('title','Add Article')

@section('content')

<br/>
<div class="container">

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
               <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form class="form" action="{{route('articles.store')}}" method="POST">
  <div class="form-group">
    <label for="name">Article Name : </label>
    <input type="text" class="form-control" name="name" placeholder="Article Name">
  </div>
  <div class="form-group">
    <label for="content">Content</label>
    <textarea class="form-control rounded-0" name="content"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

@endsection

resources/views/articles_edit.blade.php
@extends('master')

@section('title','Edit Article')

@section('content')

<br/>
<div class="container">

<form class="form" action="{{url('articles', [$articles->id])}}" method="POST">
<input type="hidden" name="_method" value="PUT">
{{ csrf_field() }}
  <div class="form-group">
    <label for="name">Article Name : </label>
    <input type="text" class="form-control" name="name" value="{{$articles->name}}" readonly>
  </div>
  <div class="form-group">
    <label for="content">Content</label>
    <textarea class="form-control" name="content">{{$articles->content}}</textarea>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

@endsection

resources/views/articles_show.blade.php
@extends('master')

@section('title','View Article')

@section('content')

<br/>
<div class="container">

<form class="form">
  <div class="form-group">
    <label for="name">Article Name : </label>
    <input type="text" class="form-control" value="{{$articles->name}}" readonly>
  </div>
  <div class="form-group">
    <label for="content">Content</label>
    <textarea class="form-control" readonly>{{$articles->content}}</textarea>
  </div>
</form>
</div>

@endsection

resources/views/home.blade.php
@extends('master')

@section('title','HomePage')

@section('content')

<br/>
<div class="container">
<a href="{{ route('articles.create') }}"><button type="button" class="btn btn-primary">ADD ARTICLE</button></a>
</div>

<div class="container">

@if(session('success'))
<br>
<div class="alert alert-success">
{{session('success')}}
</div>
@endif

<div class="container">
<br>
<table class="table table-striped">
<thead>
<tr>
<th>Article Name</th>
<th>Posted</th> 
<th colspan=3></th> 
</tr>
</thead>
<tbody>
@foreach($articles as $article)
<tr>
<td><strong>{{ $article->name}}</strong></td>
<td>{{ $article->created_at->diffForHumans() }} </td>
<td><a href="{{route('articles.show',$article->id)}}"><button type="button" class="btn btn-primary">VIEW</button></a></td>
<td><a href="{{route('articles.edit',$article->id)}}"><button type="button" class="btn btn-primary">EDIT</button></a></td>
<td><form action="{{url('articles', [$article->id])}}" method="POST">
    		<input type="hidden" name="_method" value="DELETE">
   		<input type="hidden" name="_token" value="{{ csrf_token() }}">
   		<button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">DELETE</button>
</form></td>
</tr>
@endforeach
</table>

{{ $articles->links() }}

</div>
@endsection

resources/views/master.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>@yield('title')</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

      <style>
      html, body {   
        height: 100%;
        position: relative;
      }

      footer {
        position: fixed ;
        left: 0;
        bottom: 0;
        height: 5%;
        width: 100%;
        text-align:center;
        background-color:black;
        color:white;
      }


        </style>
    </head>
    <!-- navbar navbar-expand-lg navbar-light bg-light -->
    
    <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="navbar navbar-brand">
      <a class="navbar-brand" href="#">ARTICLE</a>
    </div>
    </nav>
        @yield('content')

<footer class="footer">
      <p><strong>&copy 2019 Copyright @ VinayMahale</strong></p>
</footer>
        
    </body>
</html>